# 1. Image de base
FROM python:3.12-slim

# 2. Dossier de travail
WORKDIR /app

# 3. Installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier ton code
COPY ./app ./app

# 4. Lancer le serveur
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]